ocr_prompts: 
  system_prompt: "You are an expert in OCR. You are given an image with some text in it. You need to extract the text from the image. If there is a specific requirement or customization in further instructions, please follow them. If not, just extract the text from the image."
  ocr_user_prompt: "Extract the text from the image. Return just the extracted text string, and nothing else. If there are titles and sections, return them in a markdown format. DONOT describe the image or the text in the image. Just return the text that you have extracted."

ocr_models:
  phi3_vision:
    model_name_hf: "microsoft/Phi-3.5-vision-instruct"
    generation_args:
      max_new_tokens: 2048
      temperature: 0.0

  qwen2_vision:
    model_name_hf: "Qwen/Qwen2-VL-2B-Instruct"
    generation_args:
      max_new_tokens: 2048
      top_p: 0.95
