faster_rcnn:
  WEIGHTS_URL: "https://huggingface.co/tensorlake/faster_rcnn-publaynet/resolve/main/model_final.pth"
  WEIGHTS_FILE: "model_final.pth"
  CONFIG_FILE: "faster_rcnn_detectron2_cfg.yml" 
  LABEL_MAP:
    0: "Text"
    1: "Title"
    2: "List"
    3: "Table"
    4: "Figure"

layoutlmv3:
  WEIGHTS_URL: "https://huggingface.co/tensorlake/layoutlmv3-publaynet/resolve/main/model_final.pth"
  WEIGHTS_FILE: "model_final.pth"
  CONFIG_FILE: "cascade_layoutlmv3.yml"
  LABEL_MAP:
    0: "Text"
    1: "Title"
    2: "List"
    3: "Table"
    4: "Figure"